### ISSUE TITLE
Verifying binary data

### ISSUE THREAD

**Issue by florian-obernberger** [nguyennv/dart_pg#7]
Hey there, firstly: thank you so much for this awesome package! :)

Now, I have a hopefully small question: I have a binary file that has been detach signed with a key. How would I go about verifying this file? Because as far as I can tell the `detachVerify` method is only for clear text. Can I just convert the Uint8List to a string and then verify it? Or is there a solution that I did not find?

Thank you so much for your time and patience :)

**Comment by nguyennv** [comment]
You can do it by calling OpenPGP.createBinaryMessage and then call verifySignature method of binary message object
with OpenPGP.readSignature & verification keys

**Comment by florian-obernberger** [comment]
Thanks for the reply, it worked as expected!
